import { ROLES } from './role.constant';
import { PERMISSIONS } from './permission.constant';

export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    // User Management - Full access
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VIEW_ALL,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_STATUS_CHANGE,

    // Role Management
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_ASSIGN,

    // Doctor Management
    PERMISSIONS.DOCTOR_CREATE,
    PERMISSIONS.DOCTOR_DELETE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_VIEW_ALL,
    PERMISSIONS.DOCTOR_UPDATE,
    PERMISSIONS.DOCTOR_SCHEDULE_VIEW,
    PERMISSIONS.DOCTOR_SCHEDULE_MANAGE,
    PERMISSIONS.DOCTOR_AVAILABILITY_MANAGE,

    // Patient Management
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_VIEW_ALL,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_HISTORY_VIEW,

    // Appointment Management - Full control
    PERMISSIONS.APPOINTMENT_VIEW_ALL,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_FORCE_CANCEL,
    PERMISSIONS.APPOINTMENT_ASSIGN_DOCTOR,

    // Payment Management - Full access
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_VIEW_ALL,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.PAYMENT_VERIFY,

    // Medical Records - View only for admin purposes
    PERMISSIONS.MEDICAL_RECORD_VIEW,

    // Review Management
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.REVIEW_DELETE,

    // Notification
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_DELETE,
    PERMISSIONS.NOTIFICATION_VIEW,

    // Reports & Analytics - Full access
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_FINANCIAL,
    PERMISSIONS.REPORT_APPOINTMENT,
    PERMISSIONS.REPORT_DOCTOR_PERFORMANCE,

    // System Settings
    PERMISSIONS.SETTING_VIEW,
    PERMISSIONS.SETTING_UPDATE,
    PERMISSIONS.SETTING_SYSTEM,

    // Audit Logs
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.AUDIT_LOG_EXPORT,

    // AI Services - Moderation
    PERMISSIONS.AI_MODERATE,

    // Specialty Management
    PERMISSIONS.SPECIALTY_CREATE,
    PERMISSIONS.SPECIALTY_VIEW,
    PERMISSIONS.SPECIALTY_UPDATE,
    PERMISSIONS.SPECIALTY_DELETE
  ],

  // ==================== DOCTOR ====================
  // Medical operations, patient management, consultations
  [ROLES.DOCTOR]: [
    // Profile Management
    PERMISSIONS.USER_VIEW_PROFILE,
    PERMISSIONS.DOCTOR_UPDATE_PROFILE,

    // Schedule Management
    PERMISSIONS.DOCTOR_SCHEDULE_VIEW,
    PERMISSIONS.DOCTOR_SCHEDULE_MANAGE,
    PERMISSIONS.DOCTOR_AVAILABILITY_MANAGE,

    // Patient Management
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_HISTORY_VIEW,

    // Appointment Management
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW_OWN,
    PERMISSIONS.APPOINTMENT_CONFIRM,
    PERMISSIONS.APPOINTMENT_COMPLETE,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    // Medical Records - Full access for own patients
    PERMISSIONS.MEDICAL_RECORD_VIEW,
    PERMISSIONS.MEDICAL_RECORD_CREATE,
    PERMISSIONS.MEDICAL_RECORD_UPDATE,

    // Prescription Management
    PERMISSIONS.PRESCRIPTION_CREATE,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.PRESCRIPTION_UPDATE,

    // Consultation
    PERMISSIONS.CONSULTATION_START,
    PERMISSIONS.CONSULTATION_JOIN,
    PERMISSIONS.CONSULTATION_CHAT,
    PERMISSIONS.CONSULTATION_VIDEO,
    PERMISSIONS.CONSULTATION_END,
    PERMISSIONS.CONSULTATION_VIEW_HISTORY,

    // Payment - View related payments
    PERMISSIONS.PAYMENT_VIEW,

    // AI Services
    PERMISSIONS.AI_SUMMARY,
    PERMISSIONS.AI_DIAGNOSE_ASSIST,

    // Reviews - View only
    PERMISSIONS.REVIEW_VIEW,

    // Notification
    PERMISSIONS.NOTIFICATION_VIEW,

    // Reports - Own performance
    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.DOCTOR_UPDATE
  ],

  // ==================== USERS ====================
  // Self-service, appointments, medical records viewing
  [ROLES.USER]: [
    // Profile Management
    PERMISSIONS.USER_VIEW_PROFILE,

    // Doctor Discovery
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.DOCTOR_VIEW_ALL,
    PERMISSIONS.DOCTOR_SCHEDULE_VIEW,

    // Appointment Management
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW_OWN,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,

    // Payment Management
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_VIEW_OWN,

    // Medical Records - Own records only
    PERMISSIONS.MEDICAL_RECORD_VIEW_OWN,

    // Prescription - Own prescriptions only
    PERMISSIONS.PRESCRIPTION_VIEW_OWN,

    // Consultation
    PERMISSIONS.CONSULTATION_JOIN,
    PERMISSIONS.CONSULTATION_CHAT,
    PERMISSIONS.CONSULTATION_VIDEO,

    // AI Services
    PERMISSIONS.AI_TRIAGE,
    PERMISSIONS.AI_QA,

    // Reviews
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_VIEW,

    // Notification
    PERMISSIONS.NOTIFICATION_VIEW,

    PERMISSIONS.SPECIALTY_VIEW
  ]
} as const;

export function getPermissionsByRole(role: string): string[] {
  return DEFAULT_ROLE_PERMISSIONS[role] || [];
}
